version: 2

sources:
  - name: snowflake_sample_data
    description: 'A data source from snowflake sample data'
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
    tables:
      - name: customer
      
model:
  - name: customer_household
    description: 'A table showing customer with market secmentation as house hold'
    columns:
      - name: C_CUSTKEY
        tests:
          - unique
          - not_null

